apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=          # password
  MYSQL_DATABASE: ZGVtb2Ri                   # demodb
  MYSQL_USER: ZGVtb3VzZXI=                   # demouser
  MYSQL_PASSWORD: ZGVtb3Bhc3M=               # demopass
