name: CI/CD Pipeline for EntryTracker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set tag variable
        id: vars
        run: echo "tag=$(date +%Y%m%d)-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: tziviblau/entrytracker:${{ steps.vars.outputs.tag }}

      - name: Create KinD cluster
        uses: helm/kind-action@v1.8.0

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/mysql-secret.yaml
          kubectl apply -f k8s/mysql-service.yaml
          kubectl apply -f k8s/mysql-statefulset.yaml
          echo "Waiting for MySQL to be ready..."
          kubectl wait --for=condition=ready pod/mysql-0 --timeout=300s
          kubectl apply -f k8s/entrytracker-configmap.yaml
          kubectl apply -f k8s/entrytracker-deployment.yaml
          kubectl apply -f k8s/entrytracker-service.yaml

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
          kubectl describe pod -l app=entrytracker
